apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::435104583559:role/UdacityFlaskDeployCBKubectlRole
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-11-01T11:25:08Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1378"
  uid: 8bcebca4-7516-4b0c-81a4-a9661a6b414d
