apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::435104583559:role/UdacityFlaskDeployCBKubectlRole
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-30T17:32:06Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1409"
  uid: c35e81bb-f43b-4922-824b-998da1dfd8a0
